# urls.py
from django.urls import path 
from . import views 

urlpatterns = [
	path("", 
			views.index, name='index'),
	path("<system>/", 
		views.active, name='active'),
	path("<system>/active/", 
		views.active, name='active'),
	path("<system>/closed/", 
		views.closed, name='closed'),
	path("<system>/get_active_users/", 
		views.get_active_users, name='get_active_users'),
	path("<system>/inbound/", 
		views.inbound, name='inbound'),

	path("<system>/inbound_xml/", 
		views.inbound_xml, name='inbound_xml'),
	
	path("<system>/putawayjobrequest/", 
		views.putawayjobrequest, name='putawayjobrequest'),
	path("<system>/check_job_exists/<JobId>/", 
		views.check_job_exists, name='check_job_exists'),
	path("<system>/<JobId>/", 
		views.jobview, name='jobview'),
	path("<system>/<JobId>/accept/", 
		views.sendaccept, name='sendaccept'),
	path("<system>/<JobId>/cancelcomplete/", 
		views.sendcancelcomplete, name='sendcancelcomplete'),
	path("<system>/<JobId>/cancelreject/", 
		views.sendcancelreject, name='sendcancelreject'),
	path("<system>/<JobId>/close_job/", 
		views.close_job, name='close_job'),
	path("<system>/<JobId>/complete/", 
		views.sendcomplete, name='sendcomplete'),
	path("<system>/<JobId>/induct/", 
		views.sendinduct, name='sendinduct'),
	path("<system>/<JobId>/print/", 
		views.sendprint, name='sendprint'),
	path("<system>/<JobId>/reject/", 
		views.sendreject, name='sendreject'),
	path("<system>/<JobId>/updatecomplete/", 
		views.sendupdatecomplete, name='sendupdatecomplete'),
	path("<system>/<JobId>/updatereject/", 
		views.sendupdatereject, name='sendupdatereject'),
	path("<system>/<JobId>/<JobTaskId>/", 
		views.sendtask, name='sendtask'),
	path("<system>/<JobId>/<JobTaskId>/get_capture_field_data/", 
		views.get_capture_field_data, name='get_capture_field_data'),
	path("<system>/<JobId>/<JobTaskId>/validate_serial_number/", 
		views.validate_serial_number, name='validate_serial_number'),

]