# Generated by Django 4.2.7 on 2023-11-03 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagelocus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderjobdata',
            name='JobPriority',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='orderjobdata',
            name='JobPriorityGroup',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='orderjobdata',
            name='NextWorkArea',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='orderjobdata',
            name='SingleUnit',
            field=models.BooleanField(blank=True),
        ),
    ]
