# Generated by Django 4.2.7 on 2023-11-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagelocus', '0004_alter_ordertaskdata_itemheight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertaskdata',
            name='EventAction',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
