# Generated by Django 4.2.7 on 2023-11-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagelocus', '0005_alter_ordertaskdata_eventaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='putawaytaskdata',
            name='EventAction',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
