# Generated by Django 4.2.7 on 2023-11-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagelocus', '0006_alter_putawaytaskdata_eventaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderjobdata',
            name='JobPriority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
