# Generated by Django 4.2.7 on 2023-11-06 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagelocus', '0007_alter_orderjobdata_jobpriority'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobId', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='orderjobdata',
            name='JobDate',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='putawayjobdata',
            name='JobDate',
            field=models.CharField(max_length=25),
        ),
    ]
