# Generated by Django 4.2.7 on 2023-11-08 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagelocus', '0008_jobstatus_alter_orderjobdata_jobdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderjobdata',
            name='JobPriorityGroup',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
