# Generated by Django 4.2.7 on 2023-11-08 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagelocus', '0009_alter_orderjobdata_jobprioritygroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderjobdata',
            name='SingleUnit',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
