# Generated by Django 4.2.7 on 2023-11-08 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagelocus', '0010_alter_orderjobdata_singleunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderjobdata',
            name='NextWorkArea',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
