# Generated by Django 4.2.7 on 2023-11-08 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagelocus', '0011_alter_orderjobdata_nextworkarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertaskdata',
            name='CustOwner',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordertaskdata',
            name='Custom1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ordertaskdata',
            name='Custom10',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ordertaskdata',
            name='Custom2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ordertaskdata',
            name='Custom3',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ordertaskdata',
            name='Custom4',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ordertaskdata',
            name='Custom5',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ordertaskdata',
            name='Custom6',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ordertaskdata',
            name='Custom7',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ordertaskdata',
            name='Custom8',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ordertaskdata',
            name='Custom9',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ordertaskdata',
            name='EventAction',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordertaskdata',
            name='ItemColor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordertaskdata',
            name='ItemSize',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordertaskdata',
            name='ItemStyle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordertaskdata',
            name='ItemUPC',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordertaskdata',
            name='LotNo',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ordertaskdata',
            name='OrderId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordertaskdata',
            name='OrderLineId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordertaskdata',
            name='OrderTaskId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordertaskdata',
            name='OrderType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordertaskdata',
            name='SerialNo',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ordertaskdata',
            name='SiteId',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordertaskdata',
            name='TaskWorkArea',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordertaskdata',
            name='TaskZone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
