# Generated by Django 4.2.7 on 2023-11-08 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagelocus', '0012_alter_ordertaskdata_custowner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderjobdata',
            name='SingleUnit',
            field=models.BooleanField(default=False),
        ),
    ]
