# Generated by Django 4.2.7 on 2023-11-08 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagelocus', '0013_alter_orderjobdata_singleunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderjobdata',
            name='SingleUnit',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
