# Generated by Django 4.2.7 on 2023-11-08 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagelocus', '0017_alter_putawayjobdata_jobpriority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='putawayjobdata',
            name='JobPriority',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
