# Generated by Django 4.2.7 on 2023-11-08 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagelocus', '0018_alter_putawayjobdata_jobpriority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='putawayjobdata',
            name='JobPriority',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='putawaytaskdata',
            name='InnerLicensePlate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
