# Generated by Django 4.2.7 on 2023-11-09 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messagelocus', '0021_externalauth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExternalAuth',
        ),
    ]
