# Generated by Django 4.2.7 on 2023-11-11 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagelocus', '0023_externalauth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='putawayjobdata',
            name='EventInfo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
