# Generated by Django 4.2.7 on 2023-11-11 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagelocus', '0024_alter_putawayjobdata_eventinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='putawaytaskresultdata',
            name='ExecDate',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='putawaytaskresultdata',
            name='ExecQty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='putawaytaskresultdata',
            name='ExecRobot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='putawaytaskresultdata',
            name='ExecUser',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
