# Generated by Django 4.2.7 on 2023-11-13 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagelocus', '0025_alter_putawaytaskresultdata_execdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderjobdata',
            name='JobPriority',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='putawayjobdata',
            name='JobPriority',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
