# Generated by Django 4.2.7 on 2023-11-15 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messagelocus', '0026_alter_orderjobdata_jobpriority_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderJobEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventType', models.CharField(max_length=50)),
                ('JobDate', models.CharField(max_length=25)),
                ('EventInfo', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='PutawayJobEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventType', models.CharField(max_length=50)),
                ('JobDate', models.CharField(max_length=25)),
                ('EventInfo', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='JobStatus',
        ),
        migrations.RemoveField(
            model_name='orderjobdata',
            name='EventType',
        ),
        migrations.RemoveField(
            model_name='putawayjobdata',
            name='EventInfo',
        ),
        migrations.RemoveField(
            model_name='putawayjobdata',
            name='EventType',
        ),
        migrations.AddField(
            model_name='putawayjobevents',
            name='JobId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messagelocus.putawayjobdata'),
        ),
        migrations.AddField(
            model_name='orderjobevents',
            name='JobId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messagelocus.orderjobdata'),
        ),
    ]
