# Generated by Django 4.2.7 on 2023-11-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagelocus', '0027_orderjobevents_putawayjobevents_delete_jobstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertaskresultdata',
            name='CaptureLotNo',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='ordertaskresultdata',
            name='CaptureSerialNo',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='ordertaskresultdata',
            name='CaptureSerialNoQty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ordertaskresultdata',
            name='ExecDate',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='ordertaskresultdata',
            name='ExecQty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordertaskresultdata',
            name='ExecRobot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordertaskresultdata',
            name='ExecUser',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordertaskresultdata',
            name='TaskLocation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordertaskresultdata',
            name='TaskType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
