# Generated by Django 4.2.7 on 2023-11-17 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagelocus', '0028_alter_ordertaskresultdata_capturelotno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderjobdata',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='putawayjobdata',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
