# Generated by Django 4.2.7 on 2024-01-29 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagelocus', '0030_remove_ordertaskresultdata_capturelotno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalauth',
            name='csrf_token',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='externalauth',
            name='sessionid',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
