# Generated by Django 4.2.7 on 2024-01-29 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagelocus', '0031_externalauth_csrf_token_externalauth_sessionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalauth',
            name='system',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
