# Generated by Django 4.2.7 on 2024-01-30 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messagelocus', '0033_externalsystems_externalusers_delete_externalauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalusers',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
