# Generated by Django 4.2.7 on 2024-01-31 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messagelocus', '0034_externalusers_created_by'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderJobData',
            new_name='OrderJobs',
        ),
        migrations.RenameModel(
            old_name='OrderTaskResultData',
            new_name='OrderTaskResults',
        ),
        migrations.RenameModel(
            old_name='OrderTaskData',
            new_name='OrderTasks',
        ),
        migrations.RenameModel(
            old_name='PutawayJobData',
            new_name='PutawayJobs',
        ),
        migrations.RenameModel(
            old_name='PutawayTaskResultData',
            new_name='PutawayTaskResults',
        ),
        migrations.RenameModel(
            old_name='PutawayTaskData',
            new_name='PutawayTasks',
        ),
    ]
