# Generated by Django 4.2.7 on 2024-01-31 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagelocus', '0035_rename_orderjobdata_orderjobs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderjobevents',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ordertaskresults',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='putawayjobevents',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='putawaytaskresults',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
