# Generated by Django 4.2.7 on 2024-02-01 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messagelocus', '0036_orderjobevents_timestamp_ordertaskresults_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSerialNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SerialNo', models.CharField(blank=True, max_length=100, null=True)),
                ('JobId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messagelocus.orderjobs')),
                ('JobTaskId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messagelocus.ordertaskresults')),
            ],
        ),
    ]
