# Generated by Django 4.2.7 on 2024-03-21 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messagelocus', '0040_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
