# Generated by Django 4.2.7 on 2024-03-22 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messagelocus', '0043_externalservices_alter_externalsystems_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalsystems',
            name='service',
        ),
    ]
