# Generated by Django 4.2.7 on 2024-03-22 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messagelocus', '0044_remove_externalsystems_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExternalServices',
        ),
    ]
