# Generated by Django 4.2.7 on 2024-03-22 20:27

from django.db import migrations, models
import messagelocus.models


class Migration(migrations.Migration):

    dependencies = [
        ('messagelocus', '0045_delete_externalservices'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=250)),
            ],
            bases=(models.Model, messagelocus.models.ModelHelp),
        ),
    ]
