# Generated by Django 4.2.7 on 2024-03-22 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messagelocus', '0046_externalservices'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalsystems',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='messagelocus.externalservices'),
            preserve_default=False,
        ),
    ]
