# Generated by Django 4.2.7 on 2024-03-22 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('messagelocus', '0047_externalsystems_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalsystems',
            name='service',
        ),
        migrations.RemoveField(
            model_name='externalusers',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='orderjobs',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.externalsystems'),
        ),
        migrations.AlterField(
            model_name='putawayjobs',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.externalsystems'),
        ),
        migrations.DeleteModel(
            name='ExternalServices',
        ),
        migrations.DeleteModel(
            name='ExternalSystems',
        ),
        migrations.DeleteModel(
            name='ExternalUsers',
        ),
    ]
