# Generated by Django 4.2.7 on 2024-03-24 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messagelocus', '0067_remove_externalsystems_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalusers',
            name='system',
        ),
    ]
