# Generated by Django 4.2.7 on 2024-03-24 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messagelocus', '0068_remove_externalusers_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalsystems',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='externalusers',
            name='system',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='messagelocus.externalsystems'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='externalsystems',
            name='system',
            field=models.CharField(max_length=3),
        ),
    ]
