# Generated by Django 4.2.7 on 2024-03-24 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messagelocus', '0074_remove_orderjobs_system_remove_putawayjobs_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderjobs',
            name='system',
            field=models.ForeignKey(default='EW1', on_delete=django.db.models.deletion.CASCADE, to='messagelocus.externalsystems'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='putawayjobs',
            name='system',
            field=models.ForeignKey(default='EW1', on_delete=django.db.models.deletion.CASCADE, to='messagelocus.externalsystems'),
            preserve_default=False,
        ),
    ]
