# Generated by Django 4.2.7 on 2024-03-24 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messagelocus', '0075_orderjobs_system_putawayjobs_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderjobevents',
            name='JobId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='messagelocus.orderjobs'),
        ),
        migrations.AlterField(
            model_name='orderjobs',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderjobs', to='messagelocus.externalsystems'),
        ),
        migrations.AlterField(
            model_name='orderserialnumbers',
            name='JobTaskId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serialnumbers', to='messagelocus.ordertaskresults'),
        ),
        migrations.AlterField(
            model_name='ordertaskresults',
            name='JobId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskresults', to='messagelocus.orderjobs'),
        ),
        migrations.AlterField(
            model_name='ordertasks',
            name='JobId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='messagelocus.orderjobs'),
        ),
        migrations.AlterField(
            model_name='putawayjobevents',
            name='JobId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='messagelocus.putawayjobs'),
        ),
        migrations.AlterField(
            model_name='putawayjobs',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='putawayjobs', to='messagelocus.externalsystems'),
        ),
        migrations.AlterField(
            model_name='putawaytaskresults',
            name='JobId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskresults', to='messagelocus.putawayjobs'),
        ),
        migrations.AlterField(
            model_name='putawaytasks',
            name='JobId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='messagelocus.putawayjobs'),
        ),
    ]
