# Generated by Django 4.2.7 on 2024-03-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagelocus', '0076_alter_orderjobevents_jobid_alter_orderjobs_system_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalusers',
            name='csrf_token',
        ),
        migrations.AddField(
            model_name='externalusers',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
