# Generated by Django 4.2.7 on 2024-03-24 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messagelocus', '0077_remove_externalusers_csrf_token_externalusers_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalsystems',
            name='service',
        ),
    ]
