# Generated by Django 4.2.7 on 2024-03-28 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messagelocus', '0079_externalsystems_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='putawayjobevents',
            name='JobId',
        ),
        migrations.DeleteModel(
            name='OrderJobEvents',
        ),
        migrations.DeleteModel(
            name='PutawayJobEvents',
        ),
    ]
