# Generated by Django 4.2.7 on 2024-03-28 01:24

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messagelocus', '0080_remove_putawayjobevents_jobid_delete_orderjobevents_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PutawayJobResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventType', models.CharField(max_length=50)),
                ('EventInfo', models.CharField(max_length=250)),
                ('LicensePlate', models.CharField(max_length=50)),
                ('RequestId', models.CharField(max_length=50)),
                ('JobDate', models.CharField(max_length=25)),
                ('JobStatus', models.CharField(max_length=50)),
                ('JobStation', models.CharField(max_length=50)),
                ('JobRobot', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('JobId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='messagelocus.putawayjobs')),
            ],
            bases=(models.Model, core.models.ModelHelp),
        ),
        migrations.CreateModel(
            name='OrderJobResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventType', models.CharField(max_length=50)),
                ('EventInfo', models.CharField(max_length=250)),
                ('JobStatus', models.CharField(max_length=50)),
                ('JobDate', models.CharField(max_length=25)),
                ('JobStation', models.CharField(max_length=50)),
                ('RequestId', models.CharField(max_length=50)),
                ('ToteId', models.CharField(max_length=50)),
                ('JobRobot', models.CharField(max_length=50)),
                ('JobMethod', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('JobId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobresults', to='messagelocus.orderjobs')),
            ],
            bases=(models.Model, core.models.ModelHelp),
        ),
    ]
