# Generated by Django 4.2.7 on 2024-03-28 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagelocus', '0081_putawayjobresults_orderjobresults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderjobresults',
            name='JobId',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='orderjobresults',
            name='JobStatus',
            field=models.CharField(default='Completed', max_length=50),
        ),
        migrations.AlterField(
            model_name='putawayjobresults',
            name='JobId',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='putawayjobresults',
            name='JobStatus',
            field=models.CharField(default='Completed', max_length=50),
        ),
    ]
