# Generated by Django 4.2.7 on 2024-03-28 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messagelocus', '0082_alter_orderjobresults_jobid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderjobresults',
            name='job_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jobresults', to='messagelocus.orderjobs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='putawayjobresults',
            name='job_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jobresults', to='messagelocus.putawayjobs'),
            preserve_default=False,
        ),
    ]
