# Generated by Django 4.2.7 on 2024-03-28 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messagelocus', '0086_alter_orderjobresults_eventinfo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderserialnumbers',
            name='SerialNo',
        ),
        migrations.AddField(
            model_name='orderserialnumbers',
            name='ItemNo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderserialnumbers',
            name='Job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='messagelocus.orderjobresults'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderserialnumbers',
            name='JobTask',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='serialnumbers', to='messagelocus.ordertaskresults'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderserialnumbers',
            name='OrderId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderserialnumbers',
            name='OrderLine',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderserialnumbers',
            name='Quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orderserialnumbers',
            name='Serial',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderserialnumbers',
            name='JobId',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='orderserialnumbers',
            name='JobTaskId',
            field=models.CharField(max_length=50),
        ),
    ]
