# Generated by Django 4.2.7 on 2024-03-28 14:58

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messagelocus', '0087_remove_orderserialnumbers_serialno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PutawayJobEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventType', models.CharField(max_length=50)),
                ('JobDate', models.CharField(max_length=25)),
                ('EventInfo', models.CharField(max_length=250)),
                ('payload', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('JobId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='messagelocus.putawayjobs')),
            ],
            bases=(models.Model, core.models.ModelHelp),
        ),
        migrations.CreateModel(
            name='OrderJobEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventType', models.CharField(max_length=50)),
                ('JobDate', models.CharField(max_length=25)),
                ('EventInfo', models.CharField(max_length=250)),
                ('payload', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('JobId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='messagelocus.orderjobs')),
            ],
            bases=(models.Model, core.models.ModelHelp),
        ),
    ]
