# Generated by Django 4.2.7 on 2024-03-28 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messagelocus', '0088_putawayjobevents_orderjobevents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderjobresults',
            name='message',
        ),
        migrations.RemoveField(
            model_name='putawayjobresults',
            name='message',
        ),
    ]
