# Generated by Django 4.2.7 on 2024-03-28 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messagelocus', '0090_alter_ordertaskresults_jobid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderjobevents',
            old_name='JobId',
            new_name='Job',
        ),
        migrations.RenameField(
            model_name='ordertaskresults',
            old_name='JobId',
            new_name='Job',
        ),
        migrations.RenameField(
            model_name='ordertasks',
            old_name='JobId',
            new_name='Job',
        ),
        migrations.RenameField(
            model_name='putawayjobevents',
            old_name='JobId',
            new_name='Job',
        ),
        migrations.RenameField(
            model_name='putawaytaskresults',
            old_name='JobId',
            new_name='Job',
        ),
        migrations.RenameField(
            model_name='putawaytasks',
            old_name='JobId',
            new_name='Job',
        ),
    ]
