# Generated by Django 4.2.7 on 2024-03-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagelocus', '0091_rename_jobid_orderjobevents_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderjobs',
            name='EventInfo',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='orderjobs',
            name='EventType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='putawayjobs',
            name='EventInfo',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='putawayjobs',
            name='EventType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
