# Generated by Django 4.2.7 on 2024-03-28 20:14

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagelocus', '0092_orderjobs_eventinfo_orderjobs_eventtype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PutawayRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LicensePlate', models.CharField(max_length=50)),
                ('JobDate', models.CharField(max_length=25)),
                ('JobRobot', models.CharField(blank=True, max_length=50, null=True)),
                ('ExecUser', models.CharField(blank=True, max_length=50, null=True)),
            ],
            bases=(models.Model, core.models.ModelHelp),
        ),
    ]
