# Generated by Django 4.2.7 on 2024-03-28 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messagelocus', '0093_putawayrequests'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PutawayRequests',
            new_name='PutawayJobRequests',
        ),
    ]
