# Generated by Django 4.2.7 on 2024-03-28 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messagelocus', '0094_rename_putawayrequests_putawayjobrequests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='putawayjobrequests',
            old_name='JobDate',
            new_name='RequestDate',
        ),
        migrations.RenameField(
            model_name='putawayjobrequests',
            old_name='ExecUser',
            new_name='RequestRobot',
        ),
        migrations.RenameField(
            model_name='putawayjobrequests',
            old_name='JobRobot',
            new_name='RequestUser',
        ),
    ]
