# Generated by Django 4.2.7 on 2024-03-29 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messagelocus', '0100_alter_ordertaskresults_job_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderserialnumbers',
            old_name='OrderLine',
            new_name='OrderLineId',
        ),
    ]
