# Generated by Django 4.2.7 on 2024-04-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagelocus', '0101_rename_orderline_orderserialnumbers_orderlineid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderjobs',
            name='EventInfo',
        ),
        migrations.RemoveField(
            model_name='orderjobs',
            name='EventType',
        ),
        migrations.RemoveField(
            model_name='putawayjobs',
            name='EventInfo',
        ),
        migrations.RemoveField(
            model_name='putawayjobs',
            name='EventType',
        ),
        migrations.AlterField(
            model_name='orderjobresults',
            name='EventType',
            field=models.CharField(default='ACCEPT', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderjobresults',
            name='JobRobot',
            field=models.CharField(default='TESTBOT01', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordertaskresults',
            name='ExecDate',
            field=models.CharField(default='01-01-2001', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordertaskresults',
            name='ExecQty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordertaskresults',
            name='ExecRobot',
            field=models.CharField(default='TESTBOT01', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordertaskresults',
            name='ExecUser',
            field=models.CharField(default='AREESE', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordertasks',
            name='ItemDesc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='putawayjobresults',
            name='EventType',
            field=models.CharField(default='ACCEPT', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='putawayjobresults',
            name='JobRobot',
            field=models.CharField(default='TESTBOT01', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='putawaytaskresults',
            name='ExecDate',
            field=models.CharField(default='01-01-2001', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='putawaytaskresults',
            name='ExecQty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='putawaytaskresults',
            name='ExecRobot',
            field=models.CharField(default='TESTBOT01', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='putawaytaskresults',
            name='ExecUser',
            field=models.CharField(default='AREESE', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='putawaytasks',
            name='ItemDesc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
