# Generated by Django 4.2.7 on 2024-04-01 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messagelocus', '0103_alter_orderjobresults_jobrobot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderjobevents',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='orderjobresults',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='ordertaskresults',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='putawayjobevents',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='putawayjobresults',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='putawaytaskresults',
            name='timestamp',
        ),
    ]
