# Generated by Django 4.2.7 on 2024-04-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagelocus', '0106_alter_orderserialnumbers_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderserialnumbers',
            name='EventType',
            field=models.CharField(default='SERIAL', editable=False, max_length=50),
        ),
    ]
