# Generated by Django 4.2.7 on 2024-04-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagelocus', '0107_orderserialnumbers_eventtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderserialnumbers',
            name='EventType',
            field=models.CharField(default='SERIAL', max_length=50),
        ),
    ]
