# Generated by Django 4.2.7 on 2024-04-26 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messagelocus', '0108_alter_orderserialnumbers_eventtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalusers',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='externalusers',
            name='system',
        ),
        migrations.RemoveField(
            model_name='orderjobs',
            name='system',
        ),
        migrations.RemoveField(
            model_name='putawayjobs',
            name='system',
        ),
        migrations.DeleteModel(
            name='ExternalSystems',
        ),
        migrations.DeleteModel(
            name='ExternalUsers',
        ),
    ]
