# Generated by Django 4.2.7 on 2024-03-22 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalservices',
            name='path',
            field=models.CharField(default='/', max_length=52),
            preserve_default=False,
        ),
    ]
