# Generated by Django 4.2.7 on 2024-03-22 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_externalsystems_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalsystems',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='externalsystems',
            name='system',
            field=models.CharField(max_length=3),
        ),
    ]
