# Generated by Django 4.2.7 on 2024-03-23 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_externalsystems_id_alter_externalsystems_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalusers',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='ExternalSystems',
        ),
        migrations.DeleteModel(
            name='ExternalUsers',
        ),
    ]
