# Generated by Django 4.2.7 on 2024-03-24 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_externalusers_created_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExternalServices',
        ),
    ]
