# Generated by Django 4.2.7 on 2024-04-26 17:15

import core.models
from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_delete_externalservices'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=250)),
            ],
            bases=(models.Model, core.models.ModelHelp),
        ),
        migrations.CreateModel(
            name='ExternalSystems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=250)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systems', to='core.externalservices')),
            ],
            bases=(models.Model, core.models.ModelHelp),
        ),
        migrations.CreateModel(
            name='ExternalUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('sessionid', models.CharField(max_length=32)),
                ('active', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.externalsystems')),
            ],
            bases=(models.Model, core.models.ModelHelp),
        ),
    ]
