# Generated by Django 4.2.7 on 2024-04-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalservices',
            name='id',
        ),
        migrations.AlterField(
            model_name='externalservices',
            name='service',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
