# Generated by Django 4.2.7 on 2024-04-26 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_externalservices_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalsystems',
            name='service',
        ),
    ]
