# Generated by Django 4.2.7 on 2024-04-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_externalsystems_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalservices',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='externalservices',
            name='service',
            field=models.CharField(max_length=50),
        ),
    ]
