# Generated by Django 4.2.7 on 2024-04-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_externalservices_id_alter_externalservices_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalservices',
            name='id',
        ),
        migrations.AlterField(
            model_name='externalservices',
            name='service',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
