# Generated by Django 4.2.7 on 2024-04-27 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_externalservices_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalsystems',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='systems', to='core.externalservices'),
            preserve_default=False,
        ),
    ]
