# Generated by Django 4.2.7 on 2024-04-28 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_externalsystems_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalsystems',
            name='service',
        ),
        migrations.RemoveField(
            model_name='externalusers',
            name='system',
        ),
        migrations.DeleteModel(
            name='ExternalServices',
        ),
        migrations.DeleteModel(
            name='ExternalSystems',
        ),
    ]
