# Generated by Django 4.2.7 on 2024-04-28 19:19

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_externalsystems_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalServices',
            fields=[
                ('service', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
            ],
            bases=(models.Model, core.models.ModelHelp),
        ),
    ]
