# Generated by Django 4.2.7 on 2024-04-28 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_externalsystems'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalusers',
            name='system',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.externalsystems'),
            preserve_default=False,
        ),
    ]
